### ISSUE TITLE
TikTok

### ISSUE THREAD

**Issue by lvplsss324** [ParzivalHack/Poison-MASSReporter#2]

**Comment by arbaiarbainjj-cyber** [comment]
> No description provided.

-ws-sg.tiktok.com/ws/v2?aid=1459&fpid=9&access_key=17362b4cefe2a431c4b53f51b89162e2&device_platform=web&ttwid=1|OXbdILvTFVLjuKDwFqZrevhD5DacQYL26SZanqIp-BM|1751549829|179821039effc67eae1623a1927d0d964208739ebc488c1a81bcb46ed3156b0d&Web-Sdk-Ms-Token=WQUfxyY_HsLzl-jk8LLMHKnTCGE9V2Ufefz3HY_QrFDy2_umjF-tOry_60x2v9kpEhiSL6Zmu1eDoTvJGX3m24XlTUHzT_m2us2L2dnV0d4li1HuexGO5MNh3CKPxpd9arafG3FSld7I-WmNquJB2na55w==https://www.tiktok.com/@irwan.adryan2?_t=ZS-8yojirzCAy1&_r=1
